-- TABLA DE DONDE SE PUEDE OBTENER LAS SIGUIENTES VARIABLES GLOBALES
-- SELECT CD_ALERTA, CD_SISTEMA, CD_CASO, CD_CLIENTE, CD_TIPOLOGIA FROM GORAPR.TSCA013_ALERTA WHERE CD_CASO = 216730;
DEFINE CD_ALERTA = '1161017'
DEFINE CD_SISTEMA = 'IFI'
DEFINE CD_CASO = 216730
DEFINE NU_CLIENTE = B6056045
DEFINE CD_TIPOLOGIA = 'C1'

-- CASO CON MEDIANAS Y RELEVANTES
/*DEFINE CD_ALERTA = '3882098'
DEFINE CD_SISTEMA = 'MNM'
DEFINE CD_CASO = 200155
DEFINE NU_CLIENTE = B2665436
DEFINE CD_TIPOLOGIA = 'M2'*/


-- --------------------------------------------------------------------
-- CONSULTA 0
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Detalles de Alerta
-- SICA Section: Informaci�n de cabecera, Detalle por tipolog�a
-----------------------------------------------------------------------
-- PARAMS:
--         AL.CD_ALERTA = 3878030
--        AL.CD_SISTEMA = MNM
--        AL.CD_TIPOLOGIA = M2
----------------------------------------------------------------------- 
-- SERVICE: http://localhost:8081/msca_mult_web_back_01/services/rest/AlertasService/ /3878030/MNM
SELECT
        AL.CD_SISTEMA AS cdSistema,
        AL.CD_ALERTA AS cdAlerta,
        AL.FH_ALERTA AS fhAlerta,
        AL.FH_ENVIO AS fhEnvio,
        AL.CD_TIPOLOGIA AS cdTipologia,
        AL.CD_DIVISA AS cdDivisa,
        AL.ST_ALERTA AS cdStAlerta,
        AL.TX_MOTIVO_DESCARTE AS txMotivoDescarte,
        AL.ST_REP_AUT AS stRepAut,
        AL.NU_SCORE_MC AS scoreMc,
        AL.NU_SCORE_MD AS scoreMdl,
        AL.FH_VEN_LIB_SIA AS fhVenLibSia,
        AL.FH_REP_AUT AS fhRepAut,
        AL.FH_ASIGNACION AS fhAsignacion,
        AL.FH_VEN_REV AS fhVenRev,
        AL.CD_SEG AS cdSeg,
        (SELECT NB_RAZON FROM GORAPR.TSCA018_DET_CATALOG WHERE CD_CATALOGO = 3 AND CD_DET_CATALOGO = AL.CD_PRIORI_ASIG) AS cdPrioriAsig,
        AL.NU_SESION_ORIGEN AS cdSesion,
        AL.IM_MONTO_ALERTA AS imMontoAlerta,
        AL.CD_CLIENTE AS cdCliente,
        AL.NU_CUENTA AS nuCuenta,
        AL.CD_CASO AS cdCaso,
        AL.CD_PERIODO AS cdPeriodo,
        AL.CD_CTE AS cdCte,
        CASE WHEN AL.CD_ACCION = 'D' THEN 'ALERTA' WHEN AL.CD_ACCION = 'N' THEN 'NOTIFICACION' WHEN AL.CD_ACCION = 'I' THEN 'INEPA' END AS cdAccion,
        NVL(AL.NB_NOMBRE,NVL(AL.NB_CTE,AL.NB_NOMBRE_CTE)) AS nbCte,
        (SELECT NB_PERSONA FROM GORAPR.TSCA043_TP_PERSONA WHERE TP_PERSONA = AL.TP_PER_JURI) AS tpPerJuri,
        (SELECT CD_OFICINA || ' - ' ||NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = AL.CD_OFICINA_GEST) AS cdOficinaGest,
        AL.NB_BANCA AS nbBanca,
        AL.CD_MATCH AS cdMatch,
        AL.IM_SCORE AS imScore,
        AL.CT_MOVIMIENTO AS ctMovimiento,
        AL.CD_DIRECTA AS cdDirecta,
        AL.NU_SCORE_CORTE AS nuScoreCorte,
        NVL(AL.NB_NOMBRE,NVL(AL.NB_CTE,AL.NB_NOMBRE_CTE)) AS nbNombreCte,
        AL.NB_APPATERNO_CTE AS nbAppaternoCte,
        AL.NB_APMATERNO_CTE AS nbApmaternoCte,
        AL.NU_OPER AS nuOper,
        AL.FH_NAC AS fhNac,
        AL.NU_EDAD AS nuEdad,
        AL.CD_SECTOR AS cdSector,
        AL.FH_APERTURA AS fhApertura,
        AL.NB_SUC_APERTURA AS nbSucApertura,
        AL.CD_CENTRO_SUP AS cdCentroSup,
        AL.NB_DIVISION AS nbDivision,
        AL.NB_ESTADO AS nbEstado,
        AL.NB_ACT_ECO_BXICO AS nbActividad,
        AL.TP_SECTOR AS tpSector,
        to_char((to_date('01-01-1900','DD-MM-RRRR')+ AL.NU_ANTIGUEDAD )-2,'DD/MM/YYYY') AS nuAntiguedad,
        AL.CD_SUCURSAL AS cdSucursal,
        AL.CD_DIR_ZONA AS cdDirZona,
        AL.FH_GEN AS fhGen,
        AL.CD_ACT_ECO_BXICO AS cdActividad,
        NVL(AL.NU_DEP,0) AS nuDep,
        NVL(AL.IM_IMPORTE_DEP,0) AS imImporteDep,
        NVL(AL.IM_IMPORTE_RET,0) AS imImporteRet,
        NVL(AL.NU_RET,0) AS nuRet,
        NVL(AL.NU_CV,0) AS nuCv,
        NVL(AL.IM_IMPORTE_CV,0) AS imImporteCv,
        NVL(AL.CD_MOV_OTRO,0) AS cdMovOtro,
        NVL(AL.IM_IMP_OTRO,0) AS imImpOtro,
        AL.NU_FOLIO_IFI AS nuFolioIfi,
        AD.FH_ULTIMA AS fhUltima,
        AD.TP_CAMBIO AS tpCambio,
        (SELECT CD_OFICINA || ' - ' ||NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = AD.CR_GESTOR_CTE) AS crGestorCte,
        AD.NU_PUNTAJE AS nuPuntaje,
        AD.IM_MENS_AUT AS imMensAut,
        AD.NU_SECUENCIA AS nuSecuencia,
        AD.NB_BENEFICIARIO AS nbBeneficiario,
        AD.NU_TRANSAC AS nuTransac,
        AD.NB_EMISOR AS nbEmisor,
        AD.ST_TRANS_BANCO AS stTransBanco,
        AD.NU_ORDENANTE AS nuOrdenante,
        AD.TP_RIESGO AS tpRiesgo,
        AD.NB_ENT_REVELADORA AS nbEntReveladora,
        AD.NB_ENT_RECEPTORA AS nbEntReceptora,
        (SELECT NB_OPERAC FROM GORAPR.TSCA029_TP_OPERAC WHERE TP_OPERAC = AD.TP_OPERACION) AS tpOperacion,
        DECODE(AD.TP_OPERACION,'R','RECIBIDAS','E','ENVIADAS') AS tpOperacionC1,
        AD.TP_INST_MONETARIO AS tpInstMonetario,
        AD.TX_PERIODO AS txPeriodo,
        AD.TX_MOTIVO_REPORTE AS txMotivoReporte,
        AD.ST_CASO_PRI_ALTA AS stCasoPriAlta,
        AD.ST_ALCANCE_PRI_ALT AS stAlcancePriAlta,
        (SELECT NB_DICTAMEN_SIA FROM GORAPR.TSCA032_DICT_SIA WHERE CD_DICTAMEN_SIA = AD.CD_DICTAMEN) AS cdDictamen,
        AD.NB_FILLER1 AS nbFiller1,
        AD.NB_FILLER2 AS nbFiller2,
        AD.IM_IN AS imIn,
        AD.CD_FOCO AS cdFoco,
        AD.CD_PRIOR_SC AS cdPriorSc,
        AD.NU_PORC_RELEV AS nuPorcRelev,
        AD.NU_PORC_MEDIAN AS nuPorcMedian,
        AD.FH_MAS_RECIENTE AS fhMasReciente,
        AD.CD_NUEVOCR AS cdNuevocr,
        AD.NB_HORA_ALERTA AS nbHoraAlerta,
        AD.NB_CAJERO AS nbCajero,
        AD.NB_MUNICIPIO AS nbMunicipio,
        AD.CD_ALERTA_DET AS cdAlertaDet,
        AD.NB_NAC_CTE AS nbNacCte,
        AD.CD_CLASIF_CTE AS cdClasifCte,
        AD.NB_ACT_ECO_PEK9 AS nbActEcoPek9,
        AD.FA_CTE_PEP AS faCtePep,
        AD.FA_CTE_AR AS faCteAr,
        AD.NU_CALIF_RSG_PAIS AS nuCalifRsgPais,
        AD.FH_REPORTADO_SIA AS fhReportadoSia,
        AD.FH_OPE_CTES_SIA AS fhOpeCtesSia,
        AD.FH_CTAS_RELA_SIA AS fhCtasRelaSia,
        AD.NU_CALIF_SIA AS nuCalifSia,
        AD.NU_RSG_EFECTIVO AS nuRsgEfectivo,
        AD.NU_RSG_DE_NEG AS nuRsgDeNeg,
        AD.NU_RSG_LISTA AS nuRsgLista,
        AD.NU_RSG_GEOGRAF AS nuRsgGeograf,
        AD.NU_ALRTS_PREV_CTE AS nuAlrtsPrevCte,
        AD.NU_CALIF_MANT AS nuCalifMant,
        AD.NU_CALIF_MATRIZ AS nuCalifMatriz,
        AD.NU_CALIF_GESTION AS nuCalifGestion,
        AD.CD_REPO_TIPOLOGIA AS cdRepoTipologia,
        AD.NU_CALIF_REPORTE AS nuCalifReporte,
        AD.NU_OPIS_TOTAL AS nuOpisTotal,
        AD.IM_OPIS_TOTAL AS imOpisTotal,
        AD.NU_OPI_RECIBIDA AS nuOpiRecibida,
        TO_NUMBER(AD.IM_OPI_RECIBIDA) AS imOpiRecibida,
        AD.NU_OPI_ENVIADA AS nuOpiEnviada,
        TO_NUMBER(AD.IM_OPI_ENVIADA) AS imOpiEnviada,
        AD.NU_OPIS_DESIGNA AS nuOpisDesigna,
        AD.IM_OPIS_DESIGNA AS imOpisDesigna,
        AD.NU_OPIS_RESTO AS nuOpisResto,
        AD.IM_OPIS_RESTO AS imOpisResto,
        AD.NU_CALIF_OPIS AS nuCalifOpis,
        AD.IM_TTL_IMPTRAS_USD AS imTtlImptras,
        AD.IM_TRAS_RECIBE_USD AS imTrasRecibeUsd,
        AD.IM_TRAS_ENVIA_USD AS imTrasEnviaUsd,
        AD.IM_TTL_IMPCHQ_USD AS imTtlImpchqUsd,
        AD.NU_CHQ_RECIBE_USD AS nuChqRecibeUsd,
        AD.NU_CHQ_ENVIA_USD AS nuChqEnviaUsd,
        AD.IM_TTL_SPEI_USD AS imTtlSpeiUsd,
        AD.NU_SPEI_RECIBE_USD AS nuSpeiRecibeUsd,
        AD.NU_SPEI_ENVIA_USD AS nuSpeiEnviaUsd,
        AD.NB_ORIGEN_OPIS AS nbOrigenOpis,
        AD.NB_DESTINO_OPIS AS nbDestinoOpis,
        AD.NU_ORIGEN_KYC AS nuOrigenKyc,
        AD.NU_DESTINO_KYC AS nuDestinoKyc,
        AD.NB_ACT_ECO AS nbActEco,
        AD.FA_ACT_ECO_RSG AS faActEcoRsg,
        AD.FA_OPRTV_EDO_CTE AS faOprtvEdoCte,
        AD.FA_OPS_EDO_RSG_CTE AS faOpsEdoRsgCte,
        AD.NU_CALIF_OPERATIVA AS nuCalifOperativa,
        AD.FH_CTE_ALTA AS fhCteAlta,
        AD.FH_CTA_APERTURA AS fhCtaApertura,
        AD.NU_ANT_RFC_EDADCTE AS nuAntRfcEdadcte,
        AD.NU_CLFANTCTECTARFC AS nuClfantctectarfc,
        AD.NU_DEP_RSG_ALTO AS nuDepRsgAlto,
        AD.NU_DEP_RSG_MED AS nuDepRsgMed,
        AD.NU_DEP_RSG_BAJO AS nuDepRsgBajo,
        AD.NU_RET_RSG_ALTO AS nuRetRsgAlto,
        AD.NU_RET_RSG_MED AS nuRetRsgMed,
        AD.NU_RET_RSG_BAJO AS nuRetRsgBajo,
        AD.NU_CALIF_DEP_RET AS nuCalifDepRet,
        AD.FA_POS_CNCLDS AS faPosCnclds,
        AD.FA_POS_LQDDS AS faPosLqdds,
        AD.NU_RSG_EFCTV AS nuRsgEfctv,
        AD.NU_RSG_NGC AS nuRsgNgc,
        AD.NU_OPIS_RECIBIDAS AS nuOpisRecibidas,
        AD.IM_OPIS_RECIBIDAS AS imOpisRecibidas,
        AD.NU_OPIS_ENVIADAS AS nuOpisEnviadas,
        AD.IM_OPIS_ENVIADAS AS imOpisEnviadas,
        AD.NU_OPIS_DESIGN AS nuOpisDesign,
        AD.IM_OPIS_DESIGN AS imOpisDesign,
        AD.NB_KYC_ORIG AS nbKycOrig,
        AD.NB_ORIG_OPIS AS nbOrigOpis,
        AD.NU_ACT_BASTANTEO AS nuActBastanteo,
        AD.FA_ACT_ECO_RIESGO AS faActEcoRiesgo,
        AD.NU_CALIF_OPRTV AS nuCalifOprtv,
        AD.FH_ALTA_CTE AS fhAltaCte,
        AD.NU_ANTG_RFC_EDADCTE AS nuAntgRfcEdadcte,
        AD.NU_CLF_ANTG_CC_RFC AS nuClfAntgCcRfc,
        AD.IM_DEP_RSG_ALTO AS imDepRsgAlto,
        AD.IM_DEP_RSG_MED AS imDepRsgMed,
        AD.IM_DEP_RSG_BAJO AS imDepRsgBajo,
        AD.IM_RET_RSG_ALTO AS imRetRsgAlto,
        AD.IM_RET_RSG_MED AS imRetRsgMed,
        AD.IM_RET_RSG_BAJO AS imRetRsgBajo,
        AD.TO_IMP_TRNS AS toImpTrns,
        AD.IM_TRNS_RCB_USD AS imTrnsRcbUsd,
        AD.IM_TRNS_ENV_USD AS imTrnsEnvUsd,
        AD.IM_TOT_CHQ AS imTotChq,
        AD.IM_CHQ_RCB_USD AS imChqRcbUsd,
        AD.IM_CHQ_ENV_USD AS imChqEnvUsd,
        AD.IM_TOT_SPEI AS imTotSpei,
        AD.IM_SPEI_RCB AS imSpeiRcb,
        AD.IM_SPEI_ENV AS imSpeiEnv,
        AD.NU_CALIF_TRNS_CHQ AS nuCalifTrnsChq,
        AD.TP_CANAL AS tpCanal,
        AD.NU_SCORE_CANAL AS nuScoreCanal,
        AD.NU_IP_IGUAL AS nuIpIgual,
        AD.NU_IP_DIF_EDOCTE AS nuIpDifEdocte,
        AD.NU_CALIF_IP AS nuCalifIp,
        AD.NU_RSG_LST AS nuRsgLst,
        AD.NU_RSG_GGRFC AS nuRsgGgrfc,
        AD.NU_CALIF_GSTN AS nuCalifGstn,
        AD.TP_OPI_ENV_RCB AS tpOpiEnvRcb,
        AD.NU_CT_MOVS14P AS nuCtMovs14p,
        AD.TO_IMPRT_14P_USD AS toImprt14pUsd,
        AD.NB_PAIS_OR AS nbPaisOr,
        AD.NB_PAIS_BE AS nbPaisBe,
        AD.NB_KYC_DES AS nbKycDes,
        AD.CT_MOVS_EFE AS ctMovsEfe,
        AD.TO_IMPRT_EFE_MXP AS toImprtEfeMxp,
        AD.CT_MOVS_TRNS AS ctMovsTrns,
        AD.TO_IMPRT_TRNS_USD AS toImprtTrnsUsd,
        AD.CT_MOVS_SPEI AS ctMovsSpei,
        AD.TO_IMPRT_SPEI_USD AS toImprtSpeiUsd,
        AD.CT_MOVS_CHQ AS ctMovsChq,
        AD.TO_IMPRT_CHQ_USD AS toImprtChqUsd,
        AD.FA_OPS_EDO_CTE AS faOpsEdoCte,
        AD.FA_OPS_EDOS_RIESGO AS faOpsEdosRiesgo,
        AD.NB_OCUPACION  AS nbOcupacion,
        AD.CT_MOVS_DES_ESPECIAL AS ctMovsDesEspecial,
        AD.TO_IMPORTE_DES_ESPECIAL AS toImporteDesEspecial,
        AD.NU_CALIF_ALT_RSG AS nuCalifAltRsg,
        AD.CT_MVS_OTRS_OPI AS ctMvsOtrsOpi,
        AD.TO_IMPORTE_OTRS_OPI AS toImporteOtrsOpi,
        AD.NU_CALIF_OTRS_OPI AS nuCalifOtrsOpi,
        AD.NU_CALIFANT_CTECTARFC AS nuCalifantCtectarfc,
        AD.NU_DEP_RSG_ALT AS nuDepRsgAlt,
        AD.NU_DEP_RSG_BAJ AS nuDepRsgBaj,
        AD.NU_RET_RSG_ALT AS nuRetRsgAlt,
        AD.NU_RET_RSG_BAJ AS nuRetRsgBaj,
        AD.NU_CALIF_DEP_RET AS nuCalifDepRet,
        NVL(AL.NB_NOMBRE,NVL(AL.NB_CTE,AL.NB_NOMBRE_CTE)) AS nbNombre, 
        (SELECT NB_BIC FROM GORAPR.TSCA105_BIC WHERE CD_BIC = (SELECT CD_CARGA FROM GORAPR.TSCA070_ALERTA_DET WHERE CD_ALERTA = AL.CD_ALERTA AND CD_SISTEMA = AL.CD_SISTEMA) ) AS cdBcoExtra,  
        AD.FH_INICIO AS fhInicio,
        AD.FH_FIN AS fhFin,
        AD.FA_ENV_INV AS nbEnvioInves,
        AD.FH_OPERACION AS fhOperacion
FROM
        GORAPR.TSCA013_ALERTA AL
        LEFT JOIN GORAPR.TSCA070_ALERTA_DET AD ON TRIM(AL.CD_ALERTA) = TRIM(AD.CD_ALERTA) AND AL.CD_SISTEMA = AD.CD_SISTEMA
WHERE 
        TRIM(AL.CD_ALERTA) = '&CD_ALERTA' AND
        AL.CD_SISTEMA = '&CD_SISTEMA' AND
        AL.CD_TIPOLOGIA = '&CD_TIPOLOGIA';								
-----------------------------------------------------------------------
-- CONSULTA 1
-- SCHEMA: GORAPR 
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Datos generales
-- SICA Section: Datos generales

SELECT DISTINCT
        T13.CD_CASO AS cdCaso,
        T16.NB_NOMBRE || ' ' || T16.NB_AP_PATERNO || ' ' || T16.NB_AP_MATERNO AS nbClienteCR2,
        T16.CD_CLIENTE AS cdClienteCR2,
        T16.NB_POBLACION || ', ' || (SELECT NB_ESTADO FROM GORAPR.TSCA120_ESTADOS WHERE CD_ESTADO = T16.CD_ESTADO) || ' - RIESGO ' || (SELECT DECODE(CD_RIESGO,0,'BAJO',1,'MEDIO',2,'ALTO') FROM GORAPR.TSCA120_ESTADOS WHERE CD_ESTADO = T16.CD_ESTADO) AS nbCiudadCR2,
        T16.NB_DIREC1 || ',  ' || T16.NB_DIREC2 || ' ' || T16.NB_DIREC3|| ''||        
        CASE 
        WHEN NB_CALLE_1 IS NOT NULL AND NB_CALLE_2 IS NOT NULL 
        THEN ', ENTRE CALLE: ' || T16.NB_CALLE_1 || ' Y ' || T16.NB_CALLE_2
        WHEN NB_CALLE_1 IS NOT NULL 
        THEN  ', ENTRE CALLE: ' || NB_CALLE_1
        ELSE  '' END || ', CP ' ||T16.CD_POSTAL  AS nbDireccionCR2,        
        (T16.CD_RFC || T16.CD_HOMONIMIA) AS cdRfcCR2,
        LTRIM(T16.NB_TEL1, 0) AS nbTelParCR2,
        LTRIM(T16.NB_TEL2, 0) AS nbTelOfiCR2,
        CASE WHEN T16.NB_NACIONALIDAD IS NOT NULL THEN 
        (SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE CD_PAIS_PU = T16.NB_NACIONALIDAD) || ' - ' || (SELECT NB_NIVEL_RIESGO FROM GORAPR.TSCA069_RIESGO_PAIS WHERE CD_ISO3 = T16.NB_NACIONALIDAD) 
        ELSE '' END AS nbNacCR2, 
        T16.FH_NACIMIENTO AS fhAltaCR2,
        T16.CD_SECTOR AS cdSectorCR2,
        TO_CHAR(ROUND((SYSDATE-T16.FH_ALTA_CTE), -1)) AS fhAntNegoCR2,
        T51.NB_ACT_BANXICO AS nbActividadBanxicoCR2,
        T16.CD_CURP AS nbCurpCR2,
        T106.NB_PAIS || ' - ' || (SELECT NB_NIVEL_RIESGO FROM GORAPR.TSCA069_RIESGO_PAIS WHERE CD_ISO3 = T16.CD_PAIS) AS nbPaisRecidenciaCR2,  
        T16.FH_ALTA_CTE AS fhAperturaCR2, 
        T53.TP_FUENTE AS tipoFuenteCR2,
        CASE WHEN T16.ST_IND_CTE = 'M'  AND (T16.ST_CONTACT = 'Y' OR  T16.ST_CONTACT = 'S') AND T16.ST_CLASIF_CTE = '7' THEN 
        'SI'
        ELSE
        'NO'
        END AS listPersonasBloq,
        CASE T34.FA_RIESGO WHEN 'A' THEN 'ALTO' WHEN  'B' THEN 'MEDIO' ELSE 'BAJO' END AS nbRiesgoCR2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_CLASIF_CTE AND CD_PARAMETRO = 20),T16.ST_CLASIF_CTE) AS clasifCteCR2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_IND_CTE AND CD_PARAMETRO = 19),T16.ST_IND_CTE) AS stIndiceCTE2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_CONTACT AND CD_PARAMETRO = 18),T16.ST_CONTACT) AS stContacto2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_CLASIF_CTE AND CD_PARAMETRO = 20),T16.ST_CLASIF_CTE)  AS stClasifCTE2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_REL_GFP AND CD_PARAMETRO = 16),T16.ST_REL_GFP) AS stRELGEP2,
        NVL((SELECT NB_VALOR_FIN || ' ' || NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE NB_VALOR_FIN = T16.ST_CALIF_CTE  AND CD_PARAMETRO = 21),T16.ST_CALIF_CTE) AS stCalifCTE2,
        T16.FH_MODIFICA AS fhUltimaCR2,
        T16.CD_CENTRO_TRABAJO AS nbOficinaCR2
FROM 
        GORAPR.TSCA016_CLIENTE T16
        LEFT JOIN GORAPR.TSCA013_ALERTA T13 ON (T13.CD_CLIENTE = T16.CD_CLIENTE AND T16.CD_CASO = T13.CD_CASO)
        LEFT JOIN GORAPR.TSCA034_KYC T34 ON T34.CD_CASO = T16.CD_CASO
        LEFT JOIN GORAPR.TSCA051_ACT_BANXICO T51 ON T51.CD_ACT_BANXICO = T16.CD_ACT_BANXICO
        LEFT JOIN GORAPR.TSCA037_SECTOR T37 ON T37.CD_SECTOR = T16.CD_SECTOR
        LEFT JOIN GORAPR.TSCA017_CUENTA T17 ON (T17.NU_CUENTA = T13.NU_CUENTA)
        LEFT JOIN GORAPR.TSCA003_OFICINA T03 ON T13.CD_OFICINA_GEST = T03.CD_OFICINA
        LEFT JOIN GORAPR.TSCA052_CLIALTRIEDET T52 ON T52.CD_CLIENTE = T16.CD_CLIENTE
        LEFT JOIN GORAPR.TSCA050_CLIALTRIE T50 ON T50.CD_CLIALTRIE = T52.CD_CLIALTRIE
        LEFT JOIN GORAPR.TSCA053_RELTIPFTE T53 ON T53.TP_FTE_PRI = T50.TP_FTE_PRI
        LEFT JOIN GORAPR.TSCA070_ALERTA_DET T70 ON (T70.CD_ALERTA = T13.CD_ALERTA AND T13.CD_SISTEMA = T70.CD_SISTEMA)
        LEFT JOIN GORAPR.TSCA106_PAIS T106 ON T16.CD_PAIS = T106.CD_PAIS_PU
WHERE 
        T13.CD_SISTEMA = '&CD_SISTEMA' AND 
        T13.CD_ALERTA = '&CD_ALERTA';
----------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- CONSULTA 2
-- M�DULO: An�lisis de casos
-- PESTA�A: Datos generales
-- SECCI�N: Oficina gestora

SELECT 
    nuFolioAlertaIR,
    cdCaso,
    nbSistemaIR,
    nuCuentaIR,
    montoIR,
    divisaIR,
    fhAlertaIR,
    fhEnvioIR,
    cdSesionIR,
    nbOficinaGestoraIR,
    nbRiesgoIR,
    nbMercadoIR,
    nbDivisionIR,
    nbFuncionarioIR
FROM
(SELECT
        T13.CD_ALERTA nuFolioAlertaIR,
        T13.CD_CASO cdCaso,
        T06.CD_SISTEMA nbSistemaIR,
        T13.NU_CUENTA nuCuentaIR,
        T13.IM_MONTO_ALERTA montoIR,
        T13.CD_DIVISA divisaIR,
        T13.FH_ALERTA fhAlertaIR,
        T13.FH_ENVIO fhEnvioIR,
        T13.CD_SESION cdSesionIR,
        (SELECT CD_OFICINA ||' '|| NB_CENTRO_RESP FROM GORAPR.TSCA065_CENTRO_RESP WHERE CD_OFICINA = T65.CD_CENTRO_RESP7) nbOficinaGestoraIR,
        (SELECT NB_RIESGO FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = T65.CD_CENTRO_RESP7) nbRiesgoIR,
        (SELECT NB_CENTRO_RESP FROM GORAPR.TSCA065_CENTRO_RESP WHERE CD_OFICINA = T65.CD_CENTRO_RESP6) nbMercadoIR,
        (SELECT CD_OFICINA ||' '|| NB_CENTRO_RESP FROM GORAPR.TSCA065_CENTRO_RESP WHERE CD_OFICINA = T65.CD_CENTRO_RESP5) nbDivisionIR,
        (
                SELECT 
                        DISTINCT (T10.NB_EMPLEADO ||' ' || T10.NB_APPATERNO ||' ' || T10.NB_APMATERNO)
                FROM 
                        GORAPR.TSCA010_SIPEMPLEADO T10, 
                        GORAPR.TSCA100_SIPPUESTO T100
                WHERE 
                        TRIM(T100.CD_PUESTO) = TRIM(T10.CD_PUESTO)
                        AND CD_USUARIO IS NOT NULL
                        AND TRIM(T100.CD_PERFIL) IN ('0001', '0022', '0041')
                        AND T10.CD_CENT_COSTO = T65.CD_CENTRO_RESP7
                        AND ROWNUM < 2
    ) nbFuncionarioIR
FROM
        GORAPR.TSCA014_CASO T14
        LEFT JOIN GORAPR.TSCA016_CLIENTE T16 ON (T14.CD_CASO = T16.CD_CASO AND T14.CD_CLIENTE = T16.CD_CLIENTE)
        LEFT JOIN GORAPR.TSCA013_ALERTA T13 ON T14.CD_CASO = T13.CD_CASO
        LEFT JOIN GORAPR.TSCA006_SISTEMA T06 ON T13.CD_SISTEMA = T06.CD_SISTEMA
        LEFT JOIN GORAPR.TSCA003_OFICINA T03 ON  T13.CD_OFICINA_GEST = T03.CD_OFICINA
        LEFT JOIN GORAPR.TSCA010_SIPEMPLEADO T10 ON T03.CD_OFICINA = T10.CD_CENT_COSTO
        LEFT JOIN GORAPR.TSCA065_CENTRO_RESP T65 ON T65.CD_OFICINA = T16.CD_OFICINA
        LEFT JOIN GORAPR.TSCA073_FUNCIONARIO T73 ON T73.CD_FUNCIONARIO = T03.CD_FUNCIONARIO
WHERE 
        T13.CD_ALERTA = '&CD_ALERTA'
        AND T13.CD_SISTEMA = '&CD_SISTEMA')
GROUP BY nuFolioAlertaIR,cdCaso,nbSistemaIR,nuCuentaIR,montoIR,divisaIR,fhAlertaIR,fhEnvioIR,cdSesionIR,nbOficinaGestoraIR,nbRiesgoIR,nbMercadoIR,nbDivisionIR,nbFuncionarioIR;								
								

-- -------------------------------------------------------------------- ESTE NOS ARROJA MÿS DE 1 RESULTADO (REVISAR)
-- CONSULTA 3
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: KYC
-- SICA Section: Datos generales
SELECT 
        cdCaso,
        nbRegSimplificado,
        nbActEconomica,
        nbOcupacion,
        nbPuestoPEP,
        nbPEP,
        nbParentescoPEP,
        nbPersRel,
        nbJusOpePesos,
        nbJusOpeDolares,
        imMonTotDepositos,
        nbLocOperar,
        fhCamAltBajRiesgo,
        fhAltAltRiesgo,
        fhUltMovAltBaj,
        nbOrigenBaja,
        nbOrigenAlta,
        nbPaisResidencia,
        nbNacionalidad,
        nbJusAperCta,
        nbProRecursos,
        nbPriFueIngresos,
        nbRieActividad,
        nuTipCliente,
        nuActEconomica,
        nuOcupacion,
        nuRegPais ,
        nuProServicios,
        nuOpeHabitual,
        nuIntervinientes,
        nuSucursal,
        nuCanCaptacion,
        nuAntiguedadPuntaje,
        nuEdad,
        nuTotal,
        nbMotRiesgo,
        txObjetoSocial,
        imTransInt,
        cdEntFedIntOri,
        cdEntFedIntDes,
        imTransNacional,
        cdEntFedNalOri,
        cdEntFedNalDes,
        imEfectivo,
        imInstrumento,
        nbIndRiesgo
FROM(
SELECT
        KYC.CD_CASO cdCaso,
        KYC.NB_REGIMEN_SIMPLIF        nbRegSimplificado,
        (SELECT NB_ACT_BANXICO FROM GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = T016.CD_ACT_BANXICO) AS nbActEconomica,
        CASE
                WHEN KYC.CD_ACTIVIDAD_ECON IS NOT NULL
                THEN KYC.CD_ACTIVIDAD_ECON || ' ' || KYC.NB_ACTIVIDAD
                ELSE (SELECT NB_ACT_BANXICO FROM GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = T016.CD_ACT_BANXICO)
        END nbOcupacion,
        KYC.NB_PUESTO_PER_PEP nbPuestoPEP,
        KYC.NB_PERSONA_PEP nbPEP,
        KYC.TP_RELACION_PEP nbParentescoPEP,
        KYC.NB_RELACION_PEP nbPersRel,
        KYC.NB_JUST_TRANS nbJusOpePesos,
        KYC.NB_JUST_EFECTIVO nbJusOpeDolares,
        REPLACE(LTRIM(KYC.TO_DEPOSITO_EFE, '0 0'),' ') imMonTotDepositos,
        (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 8 AND KYC.CD_ENT_FED_CLIENTE = NB_VALOR_FIN ) nbLocOperar,
        TO_CHAR(KYC.FH_CAMB_RIESGO,'DD/MM/YYYY') fhCamAltBajRiesgo,
        TO_CHAR(KYC.FH_ALTO_RIESGO,'DD/MM/YYYY') fhAltAltRiesgo,
        TO_CHAR(KYC.FH_MODIF_RIESGO,'DD/MM/YYYY') fhUltMovAltBaj,
        KYC.CD_ORIG_FAC_BAJO nbOrigenBaja,
        KYC.CD_ORIG_FAC_ALTO nbOrigenAlta,
        (SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE KYC.CD_PAIS_RESIDENCIA = CD_PAIS_PU) nbPaisResidencia,
        (SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE KYC.CD_NACIONALIDAD = CD_PAIS_PU ) nbNacionalidad,
        KYC.NB_JUST_CUENTA nbJusAperCta,
        KYC.NB_PROCEDENCIA_REC nbProRecursos,
        KYC.NB_FUENTE_INGRESO nbPriFueIngresos,
        DECODE(ACT.CD_RIESGO, 'A','ALTO', 'M','MEDIO', 'B','BAJO') nbRieActividad,
        KYC.NU_FAC_TP_CTE nuTipCliente,
        KYC.NU_FAC_ACT_ECON nuActEconomica,
        KYC.NU_FAC_OCUP nuOcupacion,
        KYC.NU_FAC_RGO_PAIS nuRegPais ,
        KYC.NU_FAC_PROD_SERV nuProServicios,
        KYC.NU_FAC_OP_HAB nuOpeHabitual,
        KYC.NU_FAC_INTERV nuIntervinientes,
        KYC.NU_FAC_SUC nuSucursal,
        KYC.NU_FAC_CANAL nuCanCaptacion,
        KYC.NU_FAC_ANIGUEDAD nuAntiguedadPuntaje,
        KYC.NU_FAC_EDAD nuEdad,
        KYC.NU_CALIF_TOTAL nuTotal,
        KYC.NB_MOTIVO_RIESGO nbMotRiesgo,
        ACCIONISTA.NB_NOM_ACCIO txObjetoSocial,
        REPLACE(LTRIM(KYC.IM_TRANS_INT,'0 0'),' ') imTransInt,
        (SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE KYC.CD_ENT_FED_INT_ORI = CD_PAIS_PU) cdEntFedIntOri,
        (SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE KYC.CD_ENT_FED_INT_DES = CD_PAIS_PU)  cdEntFedIntDes,
        REPLACE(LTRIM(KYC.IM_TRANS_NACIONAL,'0 0'),' ') imTransNacional,
        (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE  CD_PARAMETRO = 8 AND KYC.CD_ENT_FED_NAL_ORI = NB_VALOR_FIN) cdEntFedNalOri,
        (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE  CD_PARAMETRO = 8 AND KYC.CD_ENT_FED_NAL_DES = NB_VALOR_FIN) cdEntFedNalDes,
        REPLACE(LTRIM(KYC.IM_EFECTIVO,'0 0'),' ') imEfectivo,
        REPLACE(LTRIM(KYC.IM_INSTRUMENTO,'0'),' ') imInstrumento,
        CASE KYC.FA_RIESGO WHEN 'A' THEN 'ALTO' WHEN  'B' THEN 'MEDIO' ELSE 'BAJO' END  nbIndRiesgo
FROM
        GORAPR.TSCA034_KYC KYC,
        GORAPR.TSCA063_ACCIONISTA ACCIONISTA,
        GORAPR.TSCA068_ACT_KYC ACT,
        GORAPR.TSCA016_CLIENTE T016
WHERE
        KYC.NU_CLIENTE = ACCIONISTA.CD_CLIENTE(+) AND KYC.CD_CASO = ACCIONISTA.CD_CASO(+)
        AND KYC.NU_CLIENTE = T016.CD_CLIENTE(+) AND KYC.CD_CASO = T016.CD_CASO(+)
        AND ACT.CD_ACTIVIDAD_KYC(+) = KYC.CD_ACTIVIDAD_ECON
        AND KYC.CD_CASO = '&CD_CASO' AND KYC.NU_CLIENTE = '&NU_CLIENTE' )
GROUP BY cdCaso,nbRegSimplificado,nbActEconomica,nbOcupacion,nbPuestoPEP,nbPEP,nbParentescoPEP,nbPersRel,nbJusOpePesos,nbJusOpeDolares,imMonTotDepositos,nbLocOperar,fhCamAltBajRiesgo,fhAltAltRiesgo,fhUltMovAltBaj,nbOrigenBaja,nbOrigenAlta,nbPaisResidencia,nbNacionalidad,nbJusAperCta,nbProRecursos,nbPriFueIngresos,nbRieActividad,nuTipCliente,nuActEconomica,nuOcupacion,nuRegPais,nuProServicios,nuOpeHabitual,nuIntervinientes,nuSucursal,nuCanCaptacion,
        nuAntiguedadPuntaje,nuEdad,nuTotal,nbMotRiesgo,txObjetoSocial,imTransInt,cdEntFedIntOri,cdEntFedIntDes,imTransNacional,cdEntFedNalOri,cdEntFedNalDes,imEfectivo,imInstrumento,nbIndRiesgo    
        ;
        
        
 ------------------------------------------------------------------------------------------------ 
 -- CONSULTA 4
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Opini�n de funcionario
-- SICA Section: Cabecera 


SELECT 
     T13.CD_CASO cdCaso,
     T11.FH_ENVIO fhEnvioCuest, T13.CD_ALERTA,
     (T10.NB_EMPLEADO||' '||T10.NB_APPATERNO||' '||T10.NB_APMATERNO) nbFuncionarioCuest,
     T12.NB_VALOR_INI estatusCuest,
     T11.FH_RESPUESTA fhRespuestaCuest,
     T11.FH_VENCIMIENTO fhVencimientoCuest,
     T11.FH_VENCIMIENTO fhVencimientoCuest2
  FROM GORAPR.TSCA011_ENV_CUEST T11
   JOIN GORAPR.TSCA013_ALERTA T13
    ON (T13.CD_ALERTA = T11.CD_ALERTA AND T13.CD_SISTEMA = T11.CD_SISTEMA)
   LEFT JOIN GORAPR.TSCA010_SIPEMPLEADO T10
    ON T10.CD_USUARIO = T11.CD_USUARIO
  LEFT JOIN GORAPR.TSCA012_PARAMETRO T12
    ON T12.NU_PARAMETRO = TO_NUMBER(T11.ST_CUESTIONARIO)
  WHERE 
      T12.CD_PARAMETRO = '4'
      AND T13.CD_SISTEMA ='&CD_SISTEMA' AND T13.CD_ALERTA ='&CD_ALERTA'; --CD_SISTEMA Y CD_ALERTA son los unicos que debemos de dar
      
      
 ------------------------------------------------------------------------------------------------
 ------------------------------------------------------------------------------------------------ AJUSTAR UNA LINEA PARA QUE CORRA
 -- CONSULTA 5
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Opini�n de funcionario
-- SICA Section: Desglose     


SELECT
    T13.CD_CASO AS cdCaso,
    T09.NU_PREGUNTA AS nuPregunta,
    T08.TX_PREGUNTA AS nbPregunta,
    CASE (
        SELECT TX_RESPUESTA
        FROM GORAPR.TSCA009_RESPUESTA 
        WHERE CD_SISTEMA = '&CD_SISTEMA' AND CD_ALERTA = '&CD_ALERTA' AND NU_PREGUNTA = 0) --------- ESTE FALTA AJUSTAR 
	WHEN '1' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 1 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 6 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		ELSE NVL((SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = T09.NU_PREGUNTA AND TO_CHAR(NU_PARAMETRO) = T09.TX_RESPUESTA),
			DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA))
		END
	WHEN '2' THEN
		CASE T09.NU_PREGUNTA
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 1 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 5 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 8 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 3 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		ELSE NVL((SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = T09.NU_PREGUNTA AND TO_CHAR(NU_PARAMETRO) = T09.TX_RESPUESTA),
			DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA))
		END
		
	WHEN '3' THEN
		CASE T09.NU_PREGUNTA
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 1 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 5 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 8 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 3 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		ELSE NVL((SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = T09.NU_PREGUNTA AND TO_CHAR(NU_PARAMETRO) = T09.TX_RESPUESTA),
			DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA))
		END
	WHEN '6' THEN
		CASE T09.NU_PREGUNTA
			WHEN 1 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 3 THEN DECODE(T09.TX_RESPUESTA,'A','EMPRESA','B','SINDICATO','C','PERSONAS/TRABAJADORES','D','OTROS')
			WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 10 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			ELSE T09.TX_RESPUESTA
		END
	WHEN '7' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN '8' THEN
		CASE T09.NU_PREGUNTA
		WHEN 3 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 5 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 11 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 12 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 13 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN '9' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXT',T09.TX_RESPUESTA)
		WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 10 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'A' THEN
		CASE T09.NU_PREGUNTA
			WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'Fed','FEDERAL','Mun','MUNICIPAL','Est','ESTATAL',T09.TX_RESPUESTA)
			WHEN 2.1 THEN ( SELECT NB_RAZON FROM  GORAPR.TSCA018_DET_CATALOG WHERE CD_CATALOGO = 33 AND NB_VALOR = TRIM(T09.TX_RESPUESTA ) )
			WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 8 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
			WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 10 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 13 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 14 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			ELSE T09.TX_RESPUESTA
		END
	WHEN 'B' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 7 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 11 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'C' THEN
		CASE T09.NU_PREGUNTA
		WHEN 3 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'Fam','FAMILIAR','Com','COMERCIAL','Amb','AMBAS',T09.TX_RESPUESTA)
		WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'CC','CON CONOCIMIENTO','SC','SIN CONOCIMIENTO',T09.TX_RESPUESTA)
		WHEN 11 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 12 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 14 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 17 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 18 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 20 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'D' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 7 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 11 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 12 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'E' THEN
		CASE T09.NU_PREGUNTA
			WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'Fed','FEDERAL','Mun','MUNICIPAL','Est','ESTATAL',T09.TX_RESPUESTA)
			WHEN 2.1 THEN ( SELECT NB_RAZON FROM  GORAPR.TSCA018_DET_CATALOG WHERE CD_CATALOGO = 33 AND NB_VALOR = TRIM(T09.TX_RESPUESTA ) )
			WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 6 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 8 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
			WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 10 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 13 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			WHEN 14 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
			ELSE T09.TX_RESPUESTA
		END
	WHEN 'F' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 7 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 11 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'G' THEN
		CASE T09.NU_PREGUNTA
		WHEN 3 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 4 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 5 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'Fam','FAMILIAR','Com','COMERCIAL','Amb','AMBAS',T09.TX_RESPUESTA)
		WHEN 9 THEN DECODE(T09.TX_RESPUESTA,'CC','CON CONOCIMIENTO','SC','SIN CONOCIMIENTO',T09.TX_RESPUESTA)
		WHEN 11 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 12 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 14 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 17 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 18 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 20 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	WHEN 'H' THEN
		CASE T09.NU_PREGUNTA
		WHEN 1 THEN ( SELECT NB_ACT_BANXICO FROM  GORAPR.TSCA051_ACT_BANXICO WHERE CD_ACT_BANXICO = TRIM(T09.TX_RESPUESTA ) ) 
		WHEN 2 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 3 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 17 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 4 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 6 THEN (SELECT NB_VALOR_INI FROM GORAPR.TSCA012_PARAMETRO WHERE CD_PARAMETRO = 2 AND NU_PARAMETRO = T09.TX_RESPUESTA )
		WHEN 7 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 8 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		WHEN 11 THEN DECODE(T09.TX_RESPUESTA,'1','MEXICANO','2','EXTRANJERO',T09.TX_RESPUESTA)
		WHEN 12 THEN DECODE(T09.TX_RESPUESTA,'N','NO','S','SI',T09.TX_RESPUESTA)
		ELSE T09.TX_RESPUESTA
		END
	ELSE T09.TX_RESPUESTA
	END txtRespuesta
FROM   GORAPR.TSCA009_RESPUESTA T09
JOIN GORAPR.TSCA013_ALERTA T13 ON T13.CD_ALERTA = T09.CD_ALERTA AND T13.CD_SISTEMA = T09.CD_SISTEMA
JOIN GORAPR.TSCA008_PREGUNTA T08 ON T08.NU_PREGUNTA = T09.NU_PREGUNTA
WHERE 
    T13.CD_SISTEMA = '&CD_SISTEMA'
    AND T13.CD_ALERTA = '&CD_ALERTA'
    AND T08.TP_CUESTIONARIO = (
        SELECT TX_RESPUESTA
        FROM GORAPR.TSCA009_RESPUESTA 
        WHERE CD_SISTEMA = '&CD_SISTEMA' AND CD_ALERTA = '&CD_ALERTA' AND NU_PREGUNTA = 0
    )
ORDER BY 
    T09.NU_PREGUNTA;

------------------------------------------------------------------------------------------ 
-- CONSULTA 6
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Operaciones Internacionales Enviadas y Recibidas
-- SICA Section: Agrupado de transacciones internacionales     
  
     SELECT
          cdCaso,
          numCuenta,
          tpTransaccion,
          NVL((SELECT NB_PAIS FROM GORAPR.TSCA106_PAIS WHERE CD_PAIS_UIF = cdPaisDestino),cdPaisDestino) AS cdPaisDestino,
          cdParaisoFiscal,
          nivelRiesgo,
          NVL(COUNT( cdReferencia ),0) numOperaciones,
          NVL(SUM( imInstrumento ),0) montoTransacciones,
          fhFolio
        FROM
        (
          SELECT 
            T13.CD_CASO AS cdCaso,
            T60.CD_REFERENCIA cdReferencia,
            T60.NU_CUENTA numCuenta,
            T60.FH_REPORTE fhReporte,
            T60.CD_ORG_REGULADOR orgRegulador,
            T60.CD_ENTIDAD cdEntidad,
            TO_CHAR( T60.FH_FOLIO, 'YYYY' ) fhFolio,
            DECODE(T60.TP_TRANSACC,'R','RECIBIDAS','E','ENVIADAS') tpTransaccion, --Modificacion XMX4375
            T60.NB_CORRESPONSAL nbCorresponsal,
            T60.NB_ENTIDAD_ORIGEN nbEntidadOrigen,
            T60.NB_ENTIDAD_DESTINO nbEntidadDestino,
            T60.CD_BIC_ABA cdBicAba,
            T60.NB_OPER_ORIGEN nbOperOrigen,
            T60.NB_OPER_DESTINO nbOperDest,
            T60.CD_INSTRUMENTO cdInstrumento,
            T60.NU_CLIENTE nuCliente,
            T60.CD_MONEDA cdMoneda,
            T60.IM_INST_CAMBIO imInstrumento,
            T60.CD_PAIS_ORI cdPaisOrigen,
            T60.CD_PAIS_BENEF cdPaisDestino,
            T69.NB_NIVEL_RIESGO nivelRiesgo,
            T69.CD_PARAISO_FISC cdParaisoFiscal,
            T60.FH_PROCESO anioProceso
          FROM GORAPR.TSCA060_OPIS T60
          JOIN GORAPR.TSCA013_ALERTA T13
            ON T13.CD_CASO = T60.CD_CASO  AND T13.CD_CLIENTE = T60.NU_CLIENTE
          LEFT JOIN GORAPR.TSCA069_RIESGO_PAIS T69
            ON T60.CD_PAIS_BENEF = T69.CD_ISO    
          WHERE  --T60.TP_TRANSACC = 'E' Modificacion XMX4375
          T13.CD_SISTEMA = '&CD_SISTEMA'
          AND T13.CD_ALERTA = '&CD_ALERTA'
        )
        GROUP BY cdCaso,numCuenta,tpTransaccion,nivelRiesgo,cdParaisoFiscal,cdPaisDestino,fhFolio
        ORDER BY fhFolio asc;              

--------------------------------------------------------------------------------------------
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Operaciones Relevantes
-- SICA Section: Agrupado de operaciones relevantes

--SELECT
--(SELECT NB_OPERAC FROM GORAPR.TSCA029_TP_OPERAC WHERE TRIM(TP_OPERAC) = T27.TP_OPERACION) tpOperacionOPREL,
--T27.NU_CUENTA nuCuentaOPREL,
--COUNT(T27.CD_FOLIO) nuOperacionesOPREL,
--SUM(T27.IM_MONTO) importeOPREL,
--T27.CD_DIVISA monedaOPREL
--FROM GORAPR.TSCA027_OP_RELEV T27
--WHERE T27.CD_CASO = '203427'
--AND T27.CD_CLIENTE=(SELECT CD_CLIENTE FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '20539' AND CD_SISTEMA = 'SAS')
--GROUP BY T27.TP_OPERACION, T27.CD_DIVISA, T27.NU_CUENTA;

-------------------------------------------------------------------------------------------
-- CONSULTA 7
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Operaciones Relevantes
-- SICA Section: Detalle de operaciones relevantes

SELECT
T27.CD_CASO AS cdCaso,
T27.FH_OPERACION AS fhOperacion,
T27.CD_DIVISA AS nbMoneda,
(SELECT NB_INS_MON FROM GORAPR.TSCA040_INST_MON WHERE CD_INS_MON = TO_NUMBER(T27.CD_INST_MON)) AS nbInstrumento,
(SELECT NB_OPERAC FROM GORAPR.TSCA029_TP_OPERAC WHERE TP_OPERAC = T27.TP_OPERACION) AS nbTipoTransaccion,
T27.NU_CUENTA AS nuCuentas,
T27.CD_FOLIO AS nbReferencia,
T27.IM_MONTO AS imOperacion,
T27.CD_OFICINA ||' - '||(SELECT NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = T27.CD_OFICINA) AS nbOficina,
'RELEVANTES' AS tpOperacion
FROM
GORAPR.TSCA027_OP_RELEV T27
JOIN GORAPR.TSCA016_CLIENTE T16
ON (T16.CD_CLIENTE = T27.CD_CLIENTE AND T16.CD_CASO = T27.CD_CASO)
WHERE
T27.CD_CASO = '&CD_CASO'
AND T27.CD_CLIENTE=(SELECT CD_CLIENTE FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') 
UNION ALL
SELECT
T57.CD_CASO AS cdCaso,
T57.FH_OPERACION AS fhOperacion,
T57.CD_DIVISA AS nbMoneda,
(SELECT NB_INS_MON FROM GORAPR.TSCA040_INST_MON WHERE CD_INS_MON = TO_NUMBER(T57.CD_INST_MONE)) AS nbInstrumento,
(SELECT NB_OPERAC FROM GORAPR.TSCA029_TP_OPERAC WHERE TP_OPERAC = T57.TP_OPERACION) AS nbTipoTransaccion,
T57.NU_CUENTA AS nuCuentas,
T57.CD_FOLIO AS nbReferencia,
T57.IM_IMPORTE AS imOperacion,
T57.CD_OFICINA ||' - '||(SELECT NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = T57.CD_OFICINA) AS nbOficina,
'MEDIANAS' AS tpOperacion
FROM
GORAPR.TSCA057_OP_MED T57
JOIN GORAPR.TSCA016_CLIENTE T16
ON (T16.CD_CLIENTE = T57.CD_CLIENTE AND T16.CD_CASO = T57.CD_CASO)
WHERE
T57.CD_CASO = '&CD_CASO'
AND T57.CD_CLIENTE=(SELECT CD_CLIENTE FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA');
--------------------------------------------------------------------------------------------
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Operaciones Medianas
-- SICA Section: Agrupado de operaciones medianas

--SELECT
--(SELECT NB_OPERAC FROM GORAPR.TSCA029_TP_OPERAC WHERE TRIM(TP_OPERAC) = T57.TP_OPERACION) nbOperacionesOMED,
--T57.NU_CUENTA nuCuentaOMED,
--COUNT(T57.CD_FOLIO) nuOperacionesOMED,
--SUM(T57.IM_IMPORTE) imImporteOMED,
--T57.CD_DIVISA nbMonedaOMED
--FROM GORAPR.TSCA057_OP_MED T57
--WHERE T57.CD_CASO = '203427'
--AND T57.CD_CLIENTE=(SELECT CD_CLIENTE FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '20539' AND CD_SISTEMA = 'SAS')
--GROUP BY T57.TP_OPERACION, T57.CD_DIVISA, T57.NU_CUENTA;


----------------------------------------------------------------------------------------------------

-- SCHEMA: GORAPR  --- DARLE UNA REVISADA CON ALDER 
-- SICA Module: M�dulo An�lisis
-- SICA Tab: SP_CON_OTROS_CTAS   = PARTE I DE III. CUENTAS DEL CLIENTE REPORTADO
-- 



--SELECT GORAPR.TSCA026.CD_CASO,
--GORAPR.TSCA026.CD_CLIENTE_REP,
--TO_CHAR(GORAPR.TSCA119.FH_APERTURA,'DD/MM/YYYY') FH_APERTURA,
--GORAPR.TSCA026.NU_CUENTA_PAR,
--GORAPR.TSCA119.CD_PRODUCTO,
--GORAPR.TSCA071.NB_PRODUCTO NB_PRODUCTO,
--GORAPR.TSCA119.CD_SUBPRODUCTO,
--GORAPR.TSCA071.NB_SUBPRODUCTO NB_SUBPRODUCTO,
--GORAPR.TSCA119.ST_CTA,
--GORAPR.TSCA026.CD_INTERVENCION,
--GORAPR.TSCA026.NU_SECUENCIA,
--decode(GORAPR.TSCA016.TP_PERSONA, 'F',GORAPR.TSCA016.NB_NOMBRE  || ' ' ||GORAPR.TSCA016.NB_AP_PATERNO  || ' ' ||GORAPR.TSCA016.NB_AP_MATERNO, GORAPR.TSCA016.NB_NOMBRE ||GORAPR.TSCA016.NB_AP_PATERNO || GORAPR.TSCA016.NB_AP_MATERNO) TITULAR,
--GORAPR.TSCA026.CD_CLIENTE_PAR,
--GORAPR.TSCA119.IM_SALDO,
--TO_CHAR(GORAPR.TSCA119.FH_SALDO,'DD/MM/YYYY') FH_SALDO,
--GORAPR.TSCA119.IM_PROMEDIO,
--GORAPR.TSCA119.NB_COMENTARIOS NB_COMENTARIO,
--GORAPR.TSCA119.NB_BANCA NB_BANCA,
--CD_REL_CTECTA,
--GORAPR.TSCA119.TP_CARGA TP_CARGA
--FROM   GORAPR.TSCA026_RELCTECTA TSCA026, GORAPR.TSCA119_SALDOS_CTA  TSCA119,GORAPR.TSCA071_PRD_SBPRD  TSCA071 ,GORAPR.TSCA016_CLIENTE  TSCA016
--WHERE  GORAPR.TSCA026.CD_CASO = GORAPR.TSCA119.CD_CASO(+)
--AND       GORAPR.TSCA026.CD_CASO = GORAPR.TSCA016.CD_CASO(+)
--AND      substr(GORAPR.TSCA026. NU_CUENTA_PAR,-10) = substr(GORAPR.TSCA119.CD_CUENTA_COMP(+),-10)
--AND      GORAPR.TSCA026.CD_INTERVENCION = 'T'
--AND      GORAPR.TSCA026.NU_SECUENCIA = '01'
--AND      GORAPR.TSCA026.CD_CASO = '1191938'
--AND      GORAPR.TSCA071.CD_PRODUCTO(+)    = GORAPR.TSCA119.CD_PRODUCTO
--AND      GORAPR.TSCA071.CD_SUBPRODUCTO(+) = GORAPR.TSCA119.CD_SUBPRODUCTO
--AND      GORAPR.TSCA119.CD_PRODUCTO IN ('01', '04', '11', '12', '14', '26', '27', '28', '29', '15')
--AND      GORAPR.TSCA026.CD_CLIENTE_PAR = GORAPR.TSCA016.CD_CLIENTE(+)
--AND      GORAPR.TSCA026.CD_CLIENTE_REP = (SELECT DISTINCT CD_CLIENTE FROM GORAPR.TSCA014_CASO  WHERE CD_CASO =  '1191938')
--ORDER   BY GORAPR.TSCA119.FH_APERTURA,NU_CUENTA_PAR;

----------------------------------------------------------------------------------------------------
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: SP_CON_OTROS_CTAS   = PARTE I DE III. CUENTAS DEL CLIENTE REPORTADO
-- 

--SELECT 
--    T119.CD_CASO,
--    TO_CHAR(T119.FH_APERTURA, 'DD/MM/YYYY') AS FH_APERTURA,
--    T119.CD_PRODUCTO,
--    T071.NB_PRODUCTO AS NB_PRODUCTO,
--    T119.CD_SUBPRODUCTO,
--    T071.NB_SUBPRODUCTO AS NB_SUBPRODUCTO,
--    T119.ST_CTA,
--    T119.IM_SALDO,
--    TO_CHAR(T119.FH_SALDO, 'DD/MM/YYYY') AS FH_SALDO,
--    T119.IM_PROMEDIO,
--    T119.NB_COMENTARIOS AS NB_COMENTARIO,
--    T119.NB_BANCA AS NB_BANCA,
--    T119.TP_CARGA
--FROM 
--    GORAPR.TSCA119_SALDOS_CTA T119
--    LEFT JOIN GORAPR.TSCA071_PRD_SBPRD T071
--        ON T071.CD_PRODUCTO = T119.CD_PRODUCTO
--        AND T071.CD_SUBPRODUCTO = T119.CD_SUBPRODUCTO
--WHERE 
--    T119.CD_CASO = '1191938'
--    AND T119.CD_PRODUCTO IN ('01', '04', '11', '12', '14', '26', '27', '28', '29', '15')
--ORDER BY 
--    T119.FH_APERTURA;

----------------------------------------------------------------------------------------------------
-- CONSULTA 8
-- SCHEMA: GORAPR 
-- SICA Module: M�dulo An�lisis
-- SICA Tab: SP_CON_OTROS_CTAS   = CUENTAS DEL CLIENTE REPORTADO - SIN PARTICIPES


SELECT DISTINCT
      T26.CD_CASO as cdCaso,
      T26.CD_CLIENTE_PAR cdClienteCCR,
      CASE WHEN TRIM(T26.FH_APERTURA) IS NULL THEN TO_CHAR(TCTE.FH_APERTURA_CTA,'DD/MM/YYYY') ELSE TO_CHAR(T26.FH_APERTURA,'DD/MM/YYYY') END fhAperturaCCR,
      T26.NU_CUENTA_PAR nuCuentaCCR,
      T26.NB_BLOQUEO nbEstatusCCR,
      T26.PROD nbProductoCCR,
      T26.CD_SUBPRODUCTO || ' - ' || T71.NB_SUBPRODUCTO nbSubproductoCCR,
      TCTE.ST_CLA_INTER || ' - ' || TCTE.CD_SEC_INTER || ' ' || TCTE.NOMBRE nbTitularCCR,
      TO_CHAR(TCTE.FH_CANCELACION,'DD/MM/YYYY') fhCancelacionCCR,
      '0' imSaldoCCR
    FROM (
          SELECT DISTINCT
            B.IM_SALDO,
            B.FH_APERTURA,
            A.NU_CUENTA_PAR,
            A.NB_BLOQUEO,
            A.CD_INTERVENCION,
            A.NU_SECUENCIA,
            (SELECT DISTINCT CD_PRODUCTO || ' - ' || NB_PRODUCTO FROM GORAPR.TSCA071_PRD_SBPRD WHERE CD_PRODUCTO = CASE WHEN LENGTH (TRIM(A.NU_CUENTA_PAR)) > 10 THEN SUBSTR (A.NU_CUENTA_PAR, 11, 2) ELSE SUBSTR (A.NU_CUENTA_PAR, 1, 2) END) PROD,
            B.CD_SUBPRODUCTO,
            A.CD_CASO,
            A.CD_CLIENTE_PAR,
            B.TP_CARGA,
            CASE WHEN LENGTH (TRIM (A.NU_CUENTA_PAR)) > 10 THEN SUBSTR (A.NU_CUENTA_PAR, 11, 2) ELSE SUBSTR (A.NU_CUENTA_PAR, 1, 2) END PROD_A
          FROM
            GORAPR.TSCA026_RELCTECTA A LEFT JOIN GORAPR.TSCA119_SALDOS_CTA B ON
              SUBSTR(TRIM(A.NU_CUENTA_PAR),-10) = SUBSTR(TRIM(B.CD_CUENTA_COMP),-10)
              AND A.CD_CASO = B.CD_CASO
          WHERE
            A.CD_CASO = '&CD_CASO'
            AND A.CD_CLIENTE_PAR = (SELECT DISTINCT CD_CLIENTE FROM GORAPR.TSCA014_CASO WHERE CD_CASO = A.CD_CASO)
            AND CASE WHEN LENGTH (TRIM (A.NU_CUENTA_PAR)) > 10 THEN SUBSTR (A.NU_CUENTA_PAR, 11, 2) ELSE SUBSTR (A.NU_CUENTA_PAR, 1, 2) END IN ('01', '04', '11', '12', '14', '26', '27', '28', '29')
        ) T26,
        GORAPR.TSCA071_PRD_SBPRD T71,
        (
          SELECT
            A.ST_CLA_INTER,
            A.CD_SEC_INTER,
            A.NU_CUENTA,
            CASE WHEN B.TP_PERSONA = 'F' THEN B.NB_NOMBRE || ' ' || B.NB_AP_PATERNO || ' ' || B.NB_AP_MATERNO ELSE B.NB_NOMBRE || B.NB_AP_PATERNO || B.NB_AP_MATERNO END NOMBRE,
            B.CD_CASO,
            A.FH_CANCELACION,
            A.CD_CLIENTE,
            A.FH_APERTURA_CTA
            FROM (
                  SELECT
                    A.CD_CLIENTE,
                    A.ST_CLA_INTER,
                    A.CD_SEC_INTER,
                    A.NU_CUENTA,
                    CASE WHEN A.ST_CTA IS NULL THEN NULL ELSE A.FH_CANCELACION END FH_CANCELACION,
                    CASE WHEN  TO_CHAR(FH_APERTURA_CTA,'DD/MM/YYYY') = '01/01/0001' THEN FH_ALTA_RELA_CTA ELSE FH_APERTURA_CTA END FH_APERTURA_CTA
                  FROM
                    GORAPR.TSCA101_CTE_CTA_SMD A
        ) A,
        GORAPR.TSCA016_CLIENTE B
          WHERE
            B.CD_CLIENTE = A.CD_CLIENTE(+)
            AND B.CD_CASO =  '&CD_CASO'
    ) TCTE
      WHERE
        T26.PROD_A = T71.CD_PRODUCTO(+)
        AND T26.CD_SUBPRODUCTO = T71.CD_SUBPRODUCTO(+)
        AND SUBSTR (T26.NU_CUENTA_PAR,-10) = TCTE.NU_CUENTA(+)
        AND T26.CD_CLIENTE_PAR = TCTE.CD_CLIENTE(+)
        AND(T26.TP_CARGA IS NULL OR T26.TP_CARGA = 'A');
        
 ------------------------------------------------------------------------------------
 -- CONSULTA 9
 ---- PARTICIPES DE CUENTAS CLIENTE Y OTROS PRODUCTOS
 ------------- NOTA: Nos arroja todos los clientes participes de sus Cuentas del cliente y de Productos del cliente 
 --- Podemos diferenciarlo en que los participes de "cuentas del cliente" si tiene saldo promedio y los de Otros productos no tienen saldo prom
 SELECT DISTINCT   
 T26.CD_CASO as cdCaso,
 T26.CD_CLIENTE_PAR AS nuCtePartCCR,
TRIM(T26.CD_INTERVENCION || ' ' || T26.NU_SECUENCIA || ' ' ||CASE
                  WHEN B.TP_PERSONA = 'F'
                  THEN
                        B.NB_NOMBRE
                     || ' '
                     || B.NB_AP_PATERNO
                     || ' '
                     || B.NB_AP_MATERNO
                  ELSE
                     B.NB_NOMBRE || B.NB_AP_PATERNO || B.NB_AP_MATERNO
               END) AS nbParticipesCCR ,
               to_char(NVL(C.IM_SALDO, 0 ),'999,999,999,999.00') AS imSaldoCCR,
               C.IM_PROMEDIO AS imSaldoPromCCR
FROM 
                GORAPR.TSCA026_RELCTECTA T26 , GORAPR.TSCA016_CLIENTE B , GORAPR.TSCA119_SALDOS_CTA C
            WHERE 
                  T26.CD_CASO = TRIM('&CD_CASO')
                  --AND substr(T26.NU_CUENTA_PAR,-10) = substr(TRIM(V_NU_CUENTA),-10)
                  AND T26.CD_CLIENTE_PAR != TRIM('&NU_CLIENTE') -------------------------------- Este V_TITULAR es el NUMERO_CLIENTE  
                  AND T26.CD_CLIENTE_PAR = TRIM(B.CD_CLIENTE(+))
                  AND substr(T26.NU_CUENTA_PAR,-10) =  SUBSTR (TRIM (C.CD_CUENTA_COMP(+)),-10);



----------------------------------------------------------------------------------------------------
-- CONSULTA 10
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: PARTE DE OTRAS PRODUCTOS DEL CLIENTE 
SELECT DISTINCT
       T26.CD_CASO as cdCaso,
       T26.CD_CLIENTE_PAR cdClienteCCR,
       TO_CHAR(TCTE.FH_APERTURA,'DD/MM/YYYY') fhAperturaCCR,
       /*to_char(trunc (TCTE.FH_APERTURA ), 'DD') diaAperturaCCR,
        to_char(trunc (TCTE.FH_APERTURA), 'MON') mesAperturaCCR,
        to_char(trunc (TCTE.FH_APERTURA), 'RRRR') anoAperturaCCR,*/
       T26.NU_CUENTA_PAR nuCuentaCCR,
       T26.NB_BLOQUEO nbEstatusCCR,
       T26.PROD nbProductoCCR,       
       TCTE.ST_CLA_INTER || ' - ' || TCTE.CD_SEC_INTER || ' ' || TCTE.NOMBRE nbTitularCCR,
       TO_CHAR(TCTE.FH_CANCELACION,'DD/MM/YYYY') fhCancelacionCCR ,
      /* to_char(trunc (TCTE.FH_CANCELACION ), 'DD') diaCancelacionCCR , 
       to_char(trunc (TCTE.FH_CANCELACION ), 'MON') mesCancelacionCCR , 
       to_char(trunc (TCTE.FH_CANCELACION ), 'RRRR') anoCancelacionCCR , */
       TO_CHAR(CASE
          WHEN   CTO.IM_LMT_CRD <1
          THEN   CTO_PAT.IM_SDO_MES_ACT 
          ELSE CTO.IM_LMT_CRD  
       END ,'999,999,999,999.00')  imLimCCR,
      TO_CHAR( CASE
          WHEN  CTO.IM_LMT_CRD <1
          THEN 0
          ELSE CTO.IM_DISPUESTO_TOT 
       END,'999,999,999,999.00')  imDispCCR ,
       '0' imSaldoCCR
  FROM (SELECT DISTINCT               
               A.NU_CUENTA_PAR,
               A.NB_BLOQUEO,
               A.CD_INTERVENCION,
               A.NU_SECUENCIA,
              case when length( C.CD_PRODUCTO || ' - ' || C.NB_PRODUCTO) >6 
              then C.CD_PRODUCTO || ' - ' || C.NB_PRODUCTO
              else 'NO EXISTE PRODUCTO EN CATALOGO ' END   PROD,               
               A.CD_CASO,    -- C.CD_SUBPRODUCTO || ' - ' || C.NB_SUBPRODUCTO,
               A.CD_CLIENTE_PAR,
               B.IM_PROMEDIO,
               CASE
                  WHEN LENGTH (TRIM (A.NU_CUENTA_PAR)) > 10
                  THEN
                     SUBSTR (A.NU_CUENTA_PAR, 11, 2)
                  ELSE
                     SUBSTR (A.NU_CUENTA_PAR, 1, 2)
               END
                  PROD_A
          FROM GORAPR.TSCA026_RELCTECTA A,
               GORAPR.tsca119_saldos_cta B,
               GORAPR.TSCA071_PRD_SBPRD C    -- , GORARP.TSCA115_SICA_ALERTA D
         WHERE     A.CD_CASO = TRIM('&CD_CASO')
               --AND A.CD_INTERVENCION = 'T'
               --AND A.NU_SECUENCIA = '01'
               AND A.CD_CLIENTE_PAR = (SELECT DISTINCT CD_CLIENTE
                                         FROM GORAPR.TSCA014_CASO
                                        WHERE CD_CASO = A.CD_CASO)
               --AND D.CD_CASO = '8933'
               AND CASE
                      WHEN LENGTH (TRIM (A.NU_CUENTA_PAR)) > 10
                      THEN
                         SUBSTR (A.NU_CUENTA_PAR, 11, 2)
                      ELSE
                         SUBSTR (A.NU_CUENTA_PAR, 1, 2)
                   END NOT IN
                      ('01', '04', '11', '12', '14', '26', '27', '28', '29')
               AND substr(TRIM (A.NU_CUENTA_PAR),-10) = substr(TRIM (B.CD_CUENTA_COMP(+)),-10)
               AND A.CD_CASO = TRIM (B.CD_CASO(+))
               AND CASE
                      WHEN LENGTH (TRIM (A.NU_CUENTA_PAR)) > 10
                      THEN
                         SUBSTR (A.NU_CUENTA_PAR, 11, 2)
                      ELSE
                         SUBSTR (A.NU_CUENTA_PAR, 1, 2)
                   END = C.CD_PRODUCTO(+)) T26,
       
       (SELECT A.ST_CLA_INTER,
               A.CD_SEC_INTER,
               A.NU_CUENTA,
               CASE
                  WHEN B.TP_PERSONA = 'F'
                  THEN
                        B.NB_NOMBRE
                     || ' '
                     || B.NB_AP_PATERNO
                     || ' '
                     || B.NB_AP_MATERNO
                  ELSE
                     B.NB_NOMBRE || B.NB_AP_PATERNO || B.NB_AP_MATERNO
               END
                  NOMBRE,
               B.CD_CASO,
               A.FH_CANCELACION,
               A.FH_APERTURA,A.CD_CLIENTE
          FROM (SELECT A.CD_CLIENTE,
                       A.ST_CLA_INTER,
                       A.CD_SEC_INTER,
                       A.NU_CUENTA,
                       CASE
                          WHEN A.ST_CTA IS NULL THEN NULL
                          ELSE A.FH_CANCELACION
                       END
                          FH_CANCELACION,
                          CASE
                          WHEN  TO_CHAR(FH_APERTURA_CTA,'DD/MM/YYYY') = '01/01/0001' THEN
                          FH_ALTA_RELA_CTA
                          ELSE
                          FH_APERTURA_CTA --AS FH_APERTURA
                       END FH_APERTURA
                  FROM GORAPR.TSCA101_CTE_CTA_SMD A
                 --WHERE A.ST_CLA_INTER = 'T' AND A.CD_SEC_INTER = '01'
                 ) A,
               GORAPR.TSCA016_CLIENTE B
         WHERE B.CD_CLIENTE = A.CD_CLIENTE(+)
         AND B.CD_CASO = TRIM('&CD_CASO')) TCTE , 
         (SELECT DISTINCT  T61.IM_LMT_CRD , T61.IM_DISPUESTO_TOT , T61.CD_CONTRATO
           FROM GORAPR.TSCA061_CONT_TDC T61
           WHERE T61.CD_CASO =  TRIM('&CD_CASO') )CTO,
          (      
           SELECT  T62.IM_SDO_MES_ACT ,  T62.CD_CONTRATO_MUV 
           FROM   GORAPR.TSCA062_CTO_PAT T62
           WHERE  T62.CD_CASO = TRIM('&CD_CASO')
           AND T62.FH_PROCESO = (SELECT MAX(FH_PROCESO) FROM GORAPR.TSCA062_CTO_PAT WHERE CD_CASO = TRIM('&CD_CASO') )) CTO_PAT
 WHERE  substr( T26.NU_CUENTA_PAR,-10)
           = substr(TCTE.NU_CUENTA(+),-10)
           AND 
               substr( T26.NU_CUENTA_PAR,-10)
            = substr(CTO.CD_CONTRATO(+),-10)
           AND
          substr( T26.NU_CUENTA_PAR,-10) = substr(CTO_PAT.CD_CONTRATO_MUV(+) ,-10)          
           AND T26.CD_CLIENTE_PAR = TCTE.CD_CLIENTE(+) ;
  ------------------------------------------------------------------------------------------------------------------------
  ------------------------------------------------------------------------------------------------------------------------
  ------------------------------------------------------------------------------------------------------------------------
  ---------------------------------------
  -- CONSULTA 11
  --- AQUI EMPIEZA LA MECANICA OPERACIONAL
   --------------------------------
  --CONSULTA DE MOVIMIENTOS Y DETALLE DE MOVIMIENTOS
  -- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Mecanica Operacional
-- SICA Section: Consulta detalle de Movimientos
SELECT 
    MOV.CD_CASO as cdCaso,
	TO_CHAR(MOV.NU_MOVIMIENTO) AS nuNumero,
	MOV.FH_OPERACION AS fhMovimiento,
	MOV.NU_CUENTA AS nuCuenta,
	CONCAT(OFI.CD_OFICINA, CONCAT(' - ',NB_OFICINA)) AS nbOficina,
	MOV.CD_REF_INTERNA AS nbConcepto,
	DECODE(MOV.ST_CARGO_ABONO,'H','ABONO','D','CARGO') AS nbTipoMovimiento,
	MOV.IM_IMPORTE AS imMonto,
	MOV.CD_DIVISA AS cdDivisa,
	MOV.IM_IMPORTE AS imEfectivo,
	CONCAT(MOV.CD_REF_INTERNA,CONCAT('EN LA SUCURSAL',CONCAT(OFI.CD_OFICINA,CONCAT(' - ',OFI.NB_OFICINA)))) AS nbDescripcion,
	MOV.NB_TERMINAL AS nbTerminal,
	MOV.NB_HORA_OPE AS nbHoraOpe,
	(SELECT CD_OFICINA || ' - ' || NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = MOV.CD_CENTRO) AS cdCentro,
	MOV.ST_CARGO_ABONO AS tpMovimiento,
	MOV.NU_CTA_BENEF AS nuCuentaBenef,
	MOV.NB_BENEFICIARIO AS nbBeneficiario,
	T051.NB_ACT_BANXICO AS nbActBanxico
FROM  
	GORAPR.TSCA019_MOV_BG MOV,
	GORAPR.TSCA003_OFICINA OFI,
	GORAPR.TSCA051_ACT_BANXICO T051
WHERE
	MOV.CD_CASO = '&CD_CASO'
	AND MOV.NU_CUENTA = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END            
	AND MOV.CD_CENTRO = OFI.CD_OFICINA 
	AND MOV.CD_ACT_BANX_BENEF = T051.CD_ACT_BANXICO(+)
	AND (
		  TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
   )
UNION
SELECT
    MOV.CD_CASO as cdCaso,
	MOV.CD_REFERENCIA AS nuNumero,
	MOV.FH_OPERACION AS fhMovimiento,
	MOV.CD_CONTRATO AS nuCuenta,
	CONCAT(OFI.CD_OFICINA, CONCAT(' - ',NB_OFICINA)) AS nbOficina,
	MOV.CD_COMERCIO AS nbConcepto,
CASE MOV.CD_OPERACION WHEN '27' THEN 'ABONO' ELSE 'CARGO' END AS nbTipoMovimiento,
	MOV.IM_OPERACION AS imMonto,
	MOV.CD_DIVISA AS cdDivisa,
	MOV.IM_OPERACION AS imEfectivo,
	MOV.NB_DES_MOV AS nbDescripcion,
'' AS nbTerminal,
	MOV.NB_HORA_OPE AS nbHoraOpe,
	''  AS cdCentro,
	CASE MOV.CD_OPERACION WHEN '27' THEN 'H' ELSE 'D' END AS tpMovimiento,
	'' AS nuCuentaBenef,
	'' AS nbBeneficiario,
	'' AS nbActBanxico
FROM  
	GORAPR.TSCA059_MOV_TC MOV, GORAPR.TSCA003_OFICINA OFI
WHERE
	MOV.CD_CASO = '&CD_CASO'
	AND MOV.CD_CONTRATO = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END            
	AND MOV.CD_OFICINA = OFI.CD_OFICINA 
	AND (
		  TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		  OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
   )   ;
	
-- CONSULTA 12
--CONSULTA DE CONTRAPARTE DE MOVIMIENTOS Y CASOS PREVIOS DE ESA CONTRAPARTE
-- SCHEMA: GORAPR
-- SICA Module: M�dulo An�lisis
-- SICA Tab: Mecanica Operacional
-- SICA Section: Consulta de movimientos y reportes previos
SELECT
    MVBG.CD_CASO as cdCaso,
	MVBG.CD_LEYENDA || ' ' || 
  CASE MVBG.CD_DIVISA
	WHEN 'USD' THEN 
		CASE MVBG.CD_LEYENDA
			WHEN 'T17' THEN 'SPID ENVIADO'
			WHEN 'T20' THEN 'SPID RECIBIDO'
			ELSE (SELECT NB_OPERACION FROM GORAPR.TSCA108_CAT_OPER WHERE CD_APLICACION = 'BG' AND TP_CODIGO = '01' AND CD_OPERERACION = MVBG.CD_LEYENDA) 
		END
	ELSE
		(SELECT NB_OPERACION FROM GORAPR.TSCA108_CAT_OPER WHERE CD_APLICACION = 'BG' AND TP_CODIGO = '01' AND CD_OPERERACION = MVBG.CD_LEYENDA) 
  END AS nbConceptoTC,
	TO_CHAR(MVBG.NU_MOVIMIENTO) AS nuMovimientosTC,
	ROUND(MVBG.IM_IMPORTE,2) AS imMontoTC,
	MVBG.CD_DIVISA AS cdDivisa,
	ROUND( MVBG.IM_IMPORTE * 100 /
		(
			SELECT 
				CASE SUM(IM_IMPORTE)
				WHEN 0 
				THEN 1 
				ELSE SUM(IM_IMPORTE) 
				END 
			FROM
				GORAPR.TSCA019_MOV_BG BG2
			WHERE
				CD_CASO = '&CD_CASO'
				AND NU_CUENTA = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END
				AND (
					TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
					OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
					OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
					OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
				)  
	),2) AS nuPorcentajeTC,
	CASE WHEN MVBG.ST_CARGO_ABONO = 'H' THEN 'ABONO' ELSE 'CARGO' END as tpMovimiento,
	MVBG.FH_OPERACION AS fhOperacion,
	MVBG.ST_CARGO_ABONO as nbTpMovimiento,
	MVBG.NU_CUENTA AS nuCuenta,
	(SELECT CD_OFICINA || ' - ' || NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = MVBG.CD_CENTRO) AS nbOficina,
	MVBG.CD_REF_INTERNA || ' EN LA SUCURSAL ' || (SELECT CD_OFICINA || ' - ' || NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = MVBG.CD_CENTRO) AS nbDescripcion,
	MVBG.NB_TERMINAL AS nbTerminal,
	MVBG.NB_HORA_OPE AS nbHoraOpe,
	(SELECT CD_OFICINA || ' - ' || NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = MVBG.CD_CENTRO) AS cdCentro,
	MVBG.NU_CTA_BENEF AS nuCuentaBenef,
	MVBG.NB_BENEFICIARIO AS nbBeneficiario,
	BANX.NB_ACT_BANXICO AS nbActBanxico,
	MVBG.CD_RFC AS cdRfc,
	MVBG.NB_INSTRUCCION AS nbInstruccion,
	MVBG.CD_CLIENTE AS cdCliente,
	MVBG.ST_MUESTRA_TT AS stMuestraTT,
  (
    SELECT LISTAGG(A.CD_CASO_SIA, ', ') WITHIN GROUP (ORDER BY A.CD_CASO_SIA)
    FROM GORAPR.TSCA217_REL_CASO_SIA A
    WHERE A.CD_CASO_SICA IN (
      SELECT CD_CASO
      FROM GORAPR.TSCA014_CASO
      WHERE CD_CLIENTE = MVBG.CD_CLIENTE
    )
  ) AS cdCasosSIA,

  (
    SELECT LISTAGG(B.NB_RAZON, ', ') WITHIN GROUP (ORDER BY A.CD_CASO_SIA)
    FROM GORAPR.TSCA217_REL_CASO_SIA A
    LEFT JOIN GORAPR.TSCA018_DET_CATALOG B ON A.CD_DECISION_FINAL = B.CD_DET_CATALOGO
    WHERE A.CD_CASO_SICA IN (
      SELECT CD_CASO
      FROM GORAPR.TSCA014_CASO
      WHERE CD_CLIENTE = MVBG.CD_CLIENTE
    )
  ) AS tpDictamen,

  (
    SELECT LISTAGG(
             (SELECT CASE 
                WHEN COUNT(*) > 0 THEN 'SI' 
                ELSE 'NO' 
              END
              FROM GORAPR.TSCA034_KYC KYC
              WHERE KYC.CD_CASO = A.CD_CASO_SICA
             ), ', ') 
    WITHIN GROUP (ORDER BY A.CD_CASO_SIA)
    FROM GORAPR.TSCA217_REL_CASO_SIA A
    WHERE A.CD_CASO_SICA IN (
      SELECT CD_CASO
      FROM GORAPR.TSCA014_CASO
      WHERE CD_CLIENTE = MVBG.CD_CLIENTE
    )
  ) AS cdPEP,

  (
    SELECT LISTAGG(TO_CHAR(A.FH_LIBERA_SIA, 'DD/MM/YYYY'), ', ')
    WITHIN GROUP (ORDER BY A.CD_CASO_SIA)
    FROM GORAPR.TSCA217_REL_CASO_SIA A
    WHERE A.CD_CASO_SICA IN (
      SELECT CD_CASO
      FROM GORAPR.TSCA014_CASO
      WHERE CD_CLIENTE = MVBG.CD_CLIENTE
    )
  ) AS fhDictamen

FROM 
  GORAPR.TSCA019_MOV_BG MVBG
  LEFT JOIN GORAPR.TSCA051_ACT_BANXICO BANX ON MVBG.CD_ACT_BANX_BENEF = BANX.CD_ACT_BANXICO
WHERE
  MVBG.CD_CASO = '&CD_CASO'
	AND MVBG.NU_CUENTA = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END
	AND (
		TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
	)
	AND MVBG.NU_CTA_BENEF IS NOT NULL
UNION
SELECT
    MTC.CD_CASO as cdCaso,
	MTC.CD_OPERACION || ' ' || (SELECT NB_OPERACION FROM GORAPR.TSCA108_CAT_OPER WHERE CD_APLICACION = 'MP' AND TP_CODIGO = '02' AND CD_OPERERACION = MTC.CD_OPERACION) AS nbConceptoTC,
	MTC.CD_REFERENCIA AS nuMovimientosTC,
	ROUND(MTC.IM_OPERACION,2) AS imMontoTC,
	MTC.CD_DIVISA AS cdDivisa,
	ROUND(MTC.IM_OPERACION * 100 /(
		SELECT
			CASE SUM(IM_OPERACION)
			WHEN 0 
			THEN 1
			ELSE SUM(IM_OPERACION)
			END
		FROM
			GORAPR.TSCA059_MOV_TC
		WHERE
			CD_CASO = '&CD_CASO'
			AND CD_CONTRATO =  (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
			AND FH_OPERACION BETWEEN 
			(SELECT ADD_MONTHS(TRUNC(FH_ASIGNACION),-4) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
			AND 
			(SELECT TRUNC(FH_ASIGNACION) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')							
	),2)AS nuPorcentajeTC,
	(SELECT CASE WHEN ST_CARGO_ABONO = 'H' THEN 'ABONO' ELSE 'CARGO' END FROM 
	GORAPR.TSCA019_MOV_BG,
	GORAPR.TSCA051_ACT_BANXICO
	WHERE 
	CD_CASO = '&CD_CASO'
	AND NU_CUENTA = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END
	AND (
		TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
	)
	AND CD_ACT_BANX_BENEF = CD_ACT_BANXICO(+)) as tpMovimiento,
	MTC.FH_OPERACION AS fhOperacion,
	(SELECT ST_CARGO_ABONO FROM 
	GORAPR.TSCA019_MOV_BG,
	GORAPR.TSCA051_ACT_BANXICO
	WHERE 
	CD_CASO = '&CD_CASO'
	AND NU_CUENTA = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END
	AND (
		TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
	)
	AND CD_ACT_BANX_BENEF = CD_ACT_BANXICO(+)) as nbTpMovimiento,
	CD_CONTRATO AS nuCuenta,
	(SELECT CD_OFICINA || ' - ' || NB_OFICINA FROM GORAPR.TSCA003_OFICINA WHERE CD_OFICINA = MTC.CD_OFICINA) AS nbOficina,
	MTC.NB_DES_MOV AS nbDescripcion,
	'' AS nbTerminal,
	MTC.NB_HORA_OPE AS nbHoraOpe,
	''  AS cdCentro,
	'' AS nuCuentaBenef,
	'' AS nbBeneficiario,
	'' AS nbActBanxico,
	'' AS cdRfc,
	'' AS nbInstruccion,
	'' AS cdCliente,
	'' AS stMuestraTT,
	'' AS cdCasosSIA,
	'' AS tpDictamen,
	'' AS cdPEP,
	'' AS fhDictamen
FROM 
	GORAPR.TSCA059_MOV_TC MTC
WHERE 
	MTC.CD_CASO = '&CD_CASO'
	AND MTC.CD_CONTRATO = CASE DECODE (LENGTH((SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')),10,0,1) WHEN 1 THEN (SELECT SUBSTR(NU_CUENTA,-10) FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') ELSE (SELECT NU_CUENTA FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA') END
	AND (
		TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(FH_ASIGNACION,'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-1),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-2),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
		OR TO_CHAR(FH_OPERACION,'MM/YYYY') = (SELECT TO_CHAR(ADD_MONTHS(FH_ASIGNACION,-3),'MM/YYYY') FROM GORAPR.TSCA013_ALERTA WHERE CD_ALERTA = '&CD_ALERTA' AND CD_SISTEMA = '&CD_SISTEMA')
	);